
model_name: gfd  


# backbone
in_channels: 3
base_channels: 64

# train stages
num_stages: 2

optimizer:  
  type: adam          
  adam:  
    lr: 0.001  
  sgd:  
    lr: 0.01  

lr_scheduler: step    
lr_step: 1          
lr_gamma: 0.9        
lr_T_max: 50         
lr_eta_min: 0        


start_epoch: 1  
nEpochs: 30  

metric_scoring: acc  

