
model_name: pose  


# loss
loss: 'Softmax'
max_epochs: 30
temp: 0.1
init_lr_E: 0.0001
step_size: 500
gamma: 0.9

lr_scheduler: step    
lr_step: 500          
lr_gamma: 0.9        
lr_T_max: 50         
lr_eta_min: 0    

# dataset
input_data: 'img'  
class_num: 23  

# train augnet
inc: 32
kernel_size: 3
augnet_lr: 0.01
w_dist_pre: 0.0001
w_close_known: 0.01
known_sim_limit: 0.95
mse_lowbound: 0

# train classifier
cls_pre: True
start_cls_pre_epoch: 1

optimizer:  
  type: adam        
  adam:  
    lr: 0.0001  


  sgd:  
    lr: 0.01  

start_epoch: 1  
nEpochs: 30  

metric_scoring: acc  
cluster_method: 'kmeans'


   