model_name: ssp  


optimizer:  
  type: adam      
  adam:  
    lr: 0.0001  
  sgd:  
    lr: 0.01  

rz_interp: bilinear  
blur_prob: 0.0  
blur_sig: [0, 1]  
jpg_prob: 0.0  
jpg_method:  
  - pil  
  - cv2  
jpg_qual: [90, 100]  
CropSize: 224  # scale images to this size  

trainsize: 256  
isPatch: true       
patch_size: 32  
aug: true       